name: Ada (GNAT)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install GNAT and gprbuild
      run: |
        sudo apt-get update
        sudo apt-get install -y gnat gprbuild

    - name: Build with gprbuild
      run: gprbuild my_hello_world.gpr
