name: Ada (GNAT)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Alire
      run: |
        curl -fsSL https://alire.ada.dev/install.sh | sh -s -- -y
        echo "$HOME/.alire/bin" >> $GITHUB_PATH

    - name: Install toolchain
      run: alr toolchain --select

    - name: Build with Alire
      run: alr build
